In [1]:
import numpy as np
import pandas as pd 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [2]:
weather_dataset = pd.read_csv('weather.csv')

In [3]:
weather_dataset.head()

temperatur rata-rata (°C)  kelembapan rata-rata (%)  curah hujan (mm)  \
0                       25.8                        87              17.0   
1                       27.1                        83              50.9   
2                       25.5                        84               0.0   
3                       26.5                        85               4.2   
4                       27.2                        79              16.8   

   penyinaran matahari (jam)  kecepatan angin rata-rata (m/s) outcome  
0                        2.2                                3   rainy  
1                        2.2                                3   rainy  
2                        1.2                                2   rainy  
3                        0.0                                2   rainy  
4                        4.4                                3   rainy

In [4]:
weather_dataset.shape

(31, 6)

In [5]:
weather_dataset['outcome'].value_counts()

outcome
rainy     14
cloudy    10
sunny      5
windy      2
Name: count, dtype: int64

In [6]:
X = weather_dataset.drop(columns='outcome', axis=1)
Y = weather_dataset['outcome']

In [7]:
print(X)

    temperatur rata-rata (°C)  kelembapan rata-rata (%)  curah hujan (mm)  \
0                        25.8                        87              17.0   
1                        27.1                        83              50.9   
2                        25.5                        84               0.0   
3                        26.5                        85               4.2   
4                        27.2                        79              16.8   
5                        28.4                        72               0.0   
6                        28.4                        73               0.0   
7                        26.3                        84               0.0   
8                        28.1                        77               7.4   
9                        28.8                        73               0.0   
10                       27.6                        76               0.0   
11                       27.8                        76               0.0   

In [8]:
print(Y)

0      rainy
1      rainy
2      rainy
3      rainy
4      rainy
5     cloudy
6      windy
7      sunny
8     cloudy
9      sunny
10    cloudy
11    cloudy
12     sunny
13    cloudy
14     windy
15     sunny
16     rainy
17     rainy
18     rainy
19    cloudy
20    cloudy
21    cloudy
22     sunny
23    cloudy
24     rainy
25    cloudy
26     rainy
27     rainy
28     rainy
29     rainy
30     rainy
Name: outcome, dtype: object


In [9]:
scaler = StandardScaler()

In [10]:
scaler.fit(X)

StandardScaler()

In [11]:
standarized_data = scaler.transform(X)

In [12]:
print(standarized_data)

[[-1.76392826  1.54774038  0.80798285 -0.69380746  0.51735674]
 [-0.2514536   0.74135464  3.57111064 -0.69380746  0.51735674]
 [-2.11296087  0.94295107 -0.57765646 -1.02167379 -0.81914817]
 [-0.94951883  1.14454751 -0.23532205 -1.41511339 -0.81914817]
 [-0.1351094  -0.06503111  0.79168121  0.02749847  0.51735674]
 [ 1.26102105 -1.47620616 -0.57765646 -0.10364807  1.85386164]
 [ 1.26102105 -1.27460973 -0.57765646  1.24060389  1.85386164]
 [-1.18220724  0.94295107 -0.57765646  1.99469645  0.51735674]
 [ 0.91198844 -0.46822398  0.02550418  0.0602851  -0.81914817]
 [ 1.72639787 -1.27460973 -0.57765646  1.76519002  0.51735674]
 [ 0.33026742 -0.66982042 -0.57765646  0.19143163 -0.81914817]
 [ 0.56295583 -0.66982042 -0.57765646 -1.21839359 -0.81914817]
 [ 0.67930003 -0.66982042 -0.57765646  1.50289696 -0.81914817]
 [ 1.49370946 -1.47620616 -0.54505319  0.4537247  -0.81914817]
 [ 1.26102105 -1.27460973 -0.57765646  1.27339052  1.85386164]
 [ 0.44661162 -0.66982042 -0.57765646  1.04388409  0.51

In [13]:
X = standarized_data
Y = weather_dataset['outcome']

In [14]:
print(X)
print(Y)

[[-1.76392826  1.54774038  0.80798285 -0.69380746  0.51735674]
 [-0.2514536   0.74135464  3.57111064 -0.69380746  0.51735674]
 [-2.11296087  0.94295107 -0.57765646 -1.02167379 -0.81914817]
 [-0.94951883  1.14454751 -0.23532205 -1.41511339 -0.81914817]
 [-0.1351094  -0.06503111  0.79168121  0.02749847  0.51735674]
 [ 1.26102105 -1.47620616 -0.57765646 -0.10364807  1.85386164]
 [ 1.26102105 -1.27460973 -0.57765646  1.24060389  1.85386164]
 [-1.18220724  0.94295107 -0.57765646  1.99469645  0.51735674]
 [ 0.91198844 -0.46822398  0.02550418  0.0602851  -0.81914817]
 [ 1.72639787 -1.27460973 -0.57765646  1.76519002  0.51735674]
 [ 0.33026742 -0.66982042 -0.57765646  0.19143163 -0.81914817]
 [ 0.56295583 -0.66982042 -0.57765646 -1.21839359 -0.81914817]
 [ 0.67930003 -0.66982042 -0.57765646  1.50289696 -0.81914817]
 [ 1.49370946 -1.47620616 -0.54505319  0.4537247  -0.81914817]
 [ 1.26102105 -1.27460973 -0.57765646  1.27339052  1.85386164]
 [ 0.44661162 -0.66982042 -0.57765646  1.04388409  0.51

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 1, random_state=5)

In [16]:
print(X.shape, X_train.shape, X_test.shape)

(31, 5) (30, 5) (1, 5)


In [17]:
classifier = svm.SVC(kernel='linear')

In [18]:
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [19]:
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [20]:
print('akurasi data training adalah = ', training_data_accuracy)

akurasi data training adalah =  0.9666666666666667


In [21]:
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [22]:
print('akurasi data testing adalah ', test_data_accuracy)

akurasi data testing adalah  1.0


In [23]:
def predict_outcome(temperature, humidity, rainfall, sunshine, wind_speed):
    if rainfall > 0:
        if rainfall > 10:
            return 'rainy'
        elif humidity > 80:
            return 'rainy'
        else:
            return 'cloudy'
    elif sunshine > 8:
        if wind_speed >= 4:
            return 'windy'
        else:
            return 'sunny'
    elif sunshine > 5:
        return 'sunny'
    elif humidity > 80:
        return 'rainy'
    else:
        return 'cloudy'

# Data input
data = {
    'temperatur_rata-rata': [25.8, 27.1, 25.5, 26.5, 27.2, 28.4, 28.4, 26.3, 28.1, 28.8, 27.6, 27.8, 27.9, 28.6, 28.4, 27.7, 26.9, 27.4, 27.1, 27.4, 27.6, 28.1, 27.6, 27.9, 26.3, 27.5, 26.7, 25.6, 26.4, 27.3, 26.9],
    'kelembapan_rata-rata': [87, 83, 84, 85, 79, 72, 73, 84, 77, 73, 76, 76, 76, 72, 73, 76, 82, 79, 82, 78, 75, 76, 77, 76, 81, 79, 86, 92, 86, 80, 84],
    'curah_hujan': [17, 50.9, 0, 4.2, 16.8, 0, 0, 0, 7.4, 0, 0, 0, 0, 0.4, 0, 0, 3, 25, 0.2, 0, 3.2, 3.6, 0, 0.5, 1.4, 0, 12, 10.4, 38.1, 25, 0.6],
    'sunshine': [2.2, 2.2, 1.2, 0, 4.4, 4, 8.1, 10.4, 4.5, 9.7, 4.9, 0.6, 8.9, 5.7, 8.2, 7.5, 3.3, 0.2, 2.7, 1.2, 5.4, 6.8, 6.4, 3.7, 7.7, 4, 2.7, 0, 0, 1, 6.2],
    'kecepatan_angin_rata-rata': [3, 3, 2, 2, 3, 4, 4, 3, 2, 3, 2, 2, 2, 2, 4, 3, 2, 2, 2, 2, 3, 4, 3, 3, 3, 2, 2, 1, 2, 3, 3],
    'outcome': ['rainy', 'rainy', 'rainy', 'rainy', 'rainy', 'cloudy', 'windy', 'sunny', 'cloudy', 'sunny', 'cloudy', 'cloudy', 'sunny', 'cloudy', 'windy', 'sunny', 'rainy', 'rainy', 'rainy', 'cloudy', 'cloudy', 'cloudy', 'sunny', 'cloudy', 'rainy', 'cloudy', 'rainy', 'rainy', 'rainy', 'rainy', 'rainy']
}

# Prediksi dan evaluasi
correct_predictions = 0
for i in range(len(data['temperatur_rata-rata'])):
    temperature = data['temperatur_rata-rata'][i]
    humidity = data['kelembapan_rata-rata'][i]
    rainfall = data['curah_hujan'][i]
    sunshine = data['sunshine'][i]
    wind_speed = data['kecepatan_angin_rata-rata'][i]
    actual_outcome = data['outcome'][i]
    
    predicted_outcome = predict_outcome(temperature, humidity, rainfall, sunshine, wind_speed)
    
    if predicted_outcome == actual_outcome:
        correct_predictions += 1
    
    print(f"Data: {i+1}")
    print(f"Temperature: {temperature}°C, Humidity: {humidity}%, Rainfall: {rainfall}mm, Sunshine: {sunshine}h, Wind Speed: {wind_speed}m/s")
    print(f"Actual Outcome: {actual_outcome}, Predicted Outcome: {predicted_outcome}")
    print()

accuracy = correct_predictions / len(data['temperatur_rata-rata'])
print(f"Accuracy: {accuracy * 100:.2f}%")


Data: 1
Temperature: 25.8°C, Humidity: 87%, Rainfall: 17mm, Sunshine: 2.2h, Wind Speed: 3m/s
Actual Outcome: rainy, Predicted Outcome: rainy

Data: 2
Temperature: 27.1°C, Humidity: 83%, Rainfall: 50.9mm, Sunshine: 2.2h, Wind Speed: 3m/s
Actual Outcome: rainy, Predicted Outcome: rainy

Data: 3
Temperature: 25.5°C, Humidity: 84%, Rainfall: 0mm, Sunshine: 1.2h, Wind Speed: 2m/s
Actual Outcome: rainy, Predicted Outcome: rainy

Data: 4
Temperature: 26.5°C, Humidity: 85%, Rainfall: 4.2mm, Sunshine: 0h, Wind Speed: 2m/s
Actual Outcome: rainy, Predicted Outcome: rainy

Data: 5
Temperature: 27.2°C, Humidity: 79%, Rainfall: 16.8mm, Sunshine: 4.4h, Wind Speed: 3m/s
Actual Outcome: rainy, Predicted Outcome: rainy

Data: 6
Temperature: 28.4°C, Humidity: 72%, Rainfall: 0mm, Sunshine: 4h, Wind Speed: 4m/s
Actual Outcome: cloudy, Predicted Outcome: cloudy

Data: 7
Temperature: 28.4°C, Humidity: 73%, Rainfall: 0mm, Sunshine: 8.1h, Wind Speed: 4m/s
Actual Outcome: windy, Predicted Outcome: windy

Data: 

In [24]:
import pickle

In [25]:
filename = 'weather_model.sav'
pickle.dump(classifier, open(filename, 'wb'))